version: "3.7"
services:
  ercanblog-next:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    container_name: ercanblog-next
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:3000"